// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pbproto.proto

package pbproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//消息体
type MsgBody struct {
	ID                   uint32   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgBody) Reset()         { *m = MsgBody{} }
func (m *MsgBody) String() string { return proto.CompactTextString(m) }
func (*MsgBody) ProtoMessage()    {}
func (*MsgBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a8d590025f8e593, []int{0}
}

func (m *MsgBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgBody.Unmarshal(m, b)
}
func (m *MsgBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgBody.Marshal(b, m, deterministic)
}
func (m *MsgBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBody.Merge(m, src)
}
func (m *MsgBody) XXX_Size() int {
	return xxx_messageInfo_MsgBody.Size(m)
}
func (m *MsgBody) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBody.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBody proto.InternalMessageInfo

func (m *MsgBody) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *MsgBody) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type LoginReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a8d590025f8e593, []int{1}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginRsp struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRsp) Reset()         { *m = LoginRsp{} }
func (m *LoginRsp) String() string { return proto.CompactTextString(m) }
func (*LoginRsp) ProtoMessage()    {}
func (*LoginRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a8d590025f8e593, []int{2}
}

func (m *LoginRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRsp.Unmarshal(m, b)
}
func (m *LoginRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRsp.Marshal(b, m, deterministic)
}
func (m *LoginRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRsp.Merge(m, src)
}
func (m *LoginRsp) XXX_Size() int {
	return xxx_messageInfo_LoginRsp.Size(m)
}
func (m *LoginRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRsp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRsp proto.InternalMessageInfo

func (m *LoginRsp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *LoginRsp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*MsgBody)(nil), "pbproto.MsgBody")
	proto.RegisterType((*LoginReq)(nil), "pbproto.LoginReq")
	proto.RegisterType((*LoginRsp)(nil), "pbproto.LoginRsp")
}

func init() { proto.RegisterFile("pbproto.proto", fileDescriptor_6a8d590025f8e593) }

var fileDescriptor_6a8d590025f8e593 = []byte{
	// 156 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x48, 0x2a, 0x28,
	0xca, 0x2f, 0xc9, 0xd7, 0x03, 0x93, 0x42, 0xec, 0x50, 0xae, 0x92, 0x2e, 0x17, 0xbb, 0x6f, 0x71,
	0xba, 0x53, 0x7e, 0x4a, 0xa5, 0x10, 0x1f, 0x17, 0x93, 0xa7, 0x8b, 0x04, 0xa3, 0x02, 0xa3, 0x06,
	0x6f, 0x10, 0x93, 0xa7, 0x8b, 0x90, 0x10, 0x17, 0x8b, 0x4b, 0x62, 0x49, 0xa2, 0x04, 0x93, 0x02,
	0xa3, 0x06, 0x4f, 0x10, 0x98, 0xad, 0x64, 0xc5, 0xc5, 0xe1, 0x93, 0x9f, 0x9e, 0x99, 0x17, 0x94,
	0x5a, 0x08, 0x92, 0xf7, 0x4b, 0xcc, 0x4d, 0x05, 0xeb, 0xe0, 0x0c, 0x02, 0xb3, 0x85, 0xa4, 0xb8,
	0x38, 0x02, 0x12, 0x8b, 0x8b, 0xcb, 0xf3, 0x8b, 0x52, 0xc0, 0xfa, 0x38, 0x83, 0xe0, 0x7c, 0x25,
	0x03, 0x98, 0xde, 0xe2, 0x02, 0x90, 0x5e, 0xe7, 0xfc, 0x94, 0x54, 0xa8, 0x6d, 0x60, 0xb6, 0x90,
	0x00, 0x17, 0xb3, 0x6f, 0x71, 0x3a, 0x54, 0x1b, 0x88, 0x99, 0xc4, 0x06, 0x76, 0xa3, 0x31, 0x20,
	0x00, 0x00, 0xff, 0xff, 0x35, 0x48, 0x0f, 0x21, 0xbd, 0x00, 0x00, 0x00,
}
